//! Image Based Lighting (IBL) support for PBR rendering.
//!
//! This module provides environment map loading, processing, and GPU resource management
//! for image-based lighting. Environment maps are loaded from equirectangular HDR images
//! and processed into the required formats (irradiance map, pre-filtered environment map,
//! and BRDF LUT) using GPU compute shaders.

mod brdf_lut;
mod cubemap;
mod equirect;
mod hdr_loader;
mod irradiance;
mod prefilter;

pub use hdr_loader::{load_hdr_from_bytes, load_hdr_from_path, HdrImage};

pub(crate) use brdf_lut::{BrdfLut, BrdfLutPipeline};
pub(crate) use cubemap::GpuCubemap;
pub(crate) use equirect::EquirectToCubePipeline;
pub(crate) use irradiance::IrradiancePipeline;
pub(crate) use prefilter::PrefilterPipeline;

use wgpu::util::DeviceExt;

// Re-export EnvironmentMap types from scene crate
pub use wgpu_engine_scene::{
    EnvironmentMap, EnvironmentMapId, EnvironmentSource, PreprocessedCubemap, PreprocessedIbl,
};

/// GPU uniform for environment map parameters (intensity, etc.).
///
/// Bound at binding 6 in the IBL bind group, updated per-frame without
/// retriggering expensive IBL texture processing.
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
struct EnvironmentUniform {
    intensity: f32,
    _padding: [u32; 3],
}

/// Size of the environment cubemap (per face).
pub const ENVIRONMENT_CUBEMAP_SIZE: u32 = 512;

/// Size of the irradiance cubemap (per face). Low resolution since irradiance is low-frequency.
pub const IRRADIANCE_CUBEMAP_SIZE: u32 = 32;

/// Size of the pre-filtered environment cubemap base level (per face).
pub const PREFILTERED_CUBEMAP_SIZE: u32 = 128;

/// Number of mip levels for the pre-filtered cubemap (roughness levels).
pub const PREFILTERED_MIP_LEVELS: u32 = 5;

/// Size of the BRDF integration LUT.
pub const BRDF_LUT_SIZE: u32 = 512;

/// Processed GPU resources for an environment map.
#[derive(Debug)]
pub(crate) struct ProcessedEnvironment {
    /// Uniform buffer for environment parameters (intensity).
    pub params_buffer: wgpu::Buffer,
    /// Bind group for sampling in fragment shader.
    pub bind_group: wgpu::BindGroup,
}

/// GPU resources and pipelines for Image Based Lighting.
///
/// This struct manages all IBL-related GPU resources including compute pipelines
/// for processing environment maps and the shared BRDF lookup table.
/// When compute shaders are unavailable (e.g. WebGL backend), only the bind group
/// layout is created and IBL processing is skipped.
pub(crate) struct IblResources {
    /// Pipeline for converting equirectangular HDR to cubemap (None without compute).
    equirect_pipeline: Option<EquirectToCubePipeline>,
    /// Pipeline for generating irradiance maps (None without compute).
    irradiance_pipeline: Option<IrradiancePipeline>,
    /// Pipeline for generating pre-filtered environment maps (None without compute).
    prefilter_pipeline: Option<PrefilterPipeline>,
    /// Pipeline for generating the BRDF LUT (None without compute).
    _brdf_lut_pipeline: Option<BrdfLutPipeline>,
    /// Shared BRDF lookup table. Always available — either computed via GPU or loaded from
    /// baked data generated by build.rs.
    pub brdf_lut: BrdfLut,
    /// Bind group layout for IBL sampling in fragment shaders.
    /// Always present — needed for pipeline layout creation even when IBL is unavailable.
    pub bind_group_layout: wgpu::BindGroupLayout,
    /// Whether compute shaders are available.
    has_compute: bool,
    /// Processed environment maps by ID, with the generation they were synced at.
    processed_environments: std::collections::HashMap<EnvironmentMapId, (ProcessedEnvironment, u64)>,
}

impl IblResources {
    /// Create new IBL resources.
    ///
    /// When `has_compute` is true, initializes all compute pipelines and generates the
    /// BRDF LUT. When false (e.g. WebGL backend), only creates the bind group layout
    /// needed for pipeline layout compatibility.
    pub fn new(device: &wgpu::Device, queue: &wgpu::Queue, has_compute: bool) -> Self {
        // Create bind group layout for IBL sampling — always needed for pipeline layouts
        let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("IBL Bind Group Layout"),
            entries: &[
                // Irradiance cubemap
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::Cube,
                        multisampled: false,
                    },
                    count: None,
                },
                // Irradiance sampler
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                    count: None,
                },
                // Pre-filtered cubemap
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::Cube,
                        multisampled: false,
                    },
                    count: None,
                },
                // Pre-filtered sampler
                wgpu::BindGroupLayoutEntry {
                    binding: 3,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                    count: None,
                },
                // BRDF LUT
                wgpu::BindGroupLayoutEntry {
                    binding: 4,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                // BRDF LUT sampler
                wgpu::BindGroupLayoutEntry {
                    binding: 5,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                    count: None,
                },
                // Environment parameters (intensity, etc.)
                wgpu::BindGroupLayoutEntry {
                    binding: 6,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        });

        if has_compute {
            let equirect_pipeline = EquirectToCubePipeline::new(device);
            let irradiance_pipeline = IrradiancePipeline::new(device);
            let prefilter_pipeline = PrefilterPipeline::new(device);
            let brdf_lut_pipeline = BrdfLutPipeline::new(device);
            let brdf_lut = brdf_lut_pipeline.generate(device, queue);

            Self {
                equirect_pipeline: Some(equirect_pipeline),
                irradiance_pipeline: Some(irradiance_pipeline),
                prefilter_pipeline: Some(prefilter_pipeline),
                _brdf_lut_pipeline: Some(brdf_lut_pipeline),
                brdf_lut,
                bind_group_layout,
                has_compute,
                processed_environments: std::collections::HashMap::new(),
            }
        } else {
            log::info!("Compute shaders unavailable — IBL environment maps will require preprocessed data.");
            // BRDF LUT is always available via baked data from build.rs
            let brdf_lut = BrdfLut::from_baked(device, queue);

            Self {
                equirect_pipeline: None,
                irradiance_pipeline: None,
                prefilter_pipeline: None,
                _brdf_lut_pipeline: None,
                brdf_lut,
                bind_group_layout,
                has_compute,
                processed_environments: std::collections::HashMap::new(),
            }
        }
    }

    /// Process an environment map, generating all required GPU resources.
    ///
    /// If the environment has already been processed (same ID), only updates
    /// the params buffer (intensity). Full texture reprocessing is skipped
    /// since the source cannot change on an existing environment map.
    ///
    /// When preprocessed IBL data is available, uploads it directly — no compute
    /// shaders needed. Otherwise, processes via GPU compute if available.
    pub fn process_environment(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        env_map: &EnvironmentMap,
    ) -> anyhow::Result<()> {
        // Already processed — just update params (intensity, etc.)
        if self.processed_environments.contains_key(&env_map.id) {
            self.update_env_params(queue, env_map);
            return Ok(());
        }

        // Try preprocessed data first (works on all platforms)
        if let Some(preprocessed) = env_map.preprocessed_ibl() {
            return self.upload_preprocessed(device, queue, env_map, preprocessed);
        }

        if !self.has_compute {
            log::warn!(
                "Skipping environment map {} (no compute shaders and no preprocessed data).",
                env_map.id
            );
            return Ok(());
        }

        self.process_from_hdr(device, queue, env_map)
    }

    /// Upload preprocessed IBL data directly to GPU textures.
    ///
    /// This path requires no compute shaders — it creates cubemap textures and
    /// uploads the pre-baked pixel data via `queue.write_texture()`.
    fn upload_preprocessed(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        env_map: &EnvironmentMap,
        preprocessed: &PreprocessedIbl,
    ) -> anyhow::Result<()> {
        let irradiance = upload_preprocessed_cubemap(
            device,
            queue,
            &preprocessed.irradiance,
            "IBL Irradiance (Preprocessed)",
        );

        let prefiltered = upload_preprocessed_cubemap(
            device,
            queue,
            &preprocessed.prefiltered,
            "IBL Prefiltered (Preprocessed)",
        );

        // TODO: support custom BRDF LUT from preprocessed.brdf_lut

        self.store_processed(device, env_map, &irradiance, &prefiltered);
        Ok(())
    }

    /// Process an environment map from HDR source via GPU compute shaders.
    fn process_from_hdr(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        env_map: &EnvironmentMap,
    ) -> anyhow::Result<()> {
        // Load HDR image from source
        let hdr_image = match env_map.source() {
            EnvironmentSource::EquirectangularPath(path) => load_hdr_from_path(path)?,
            EnvironmentSource::EquirectangularHdr(bytes) => load_hdr_from_bytes(bytes)?,
            EnvironmentSource::Preprocessed => {
                anyhow::bail!("Environment map {} has no HDR source and no preprocessed IBL data", env_map.id);
            }
        };

        // The unwraps below are safe: has_compute is true so pipelines were initialized
        let equirect = self.equirect_pipeline.as_ref().unwrap();
        let irradiance_pipeline = self.irradiance_pipeline.as_ref().unwrap();
        let prefilter_pipeline = self.prefilter_pipeline.as_ref().unwrap();

        // Convert equirectangular to cubemap
        let environment = equirect.convert(device, queue, &hdr_image);

        // Generate irradiance map
        let irradiance = irradiance_pipeline.generate(device, queue, &environment);

        // Generate pre-filtered map
        let prefiltered = prefilter_pipeline.generate(device, queue, &environment);

        self.store_processed(device, env_map, &irradiance, &prefiltered);
        Ok(())
    }

    /// Create the bind group and store the processed environment.
    fn store_processed(
        &mut self,
        device: &wgpu::Device,
        env_map: &EnvironmentMap,
        irradiance: &GpuCubemap,
        prefiltered: &GpuCubemap,
    ) {
        // Create uniform buffer for environment parameters
        let env_uniform = EnvironmentUniform {
            intensity: env_map.intensity(),
            _padding: [0; 3],
        };
        let params_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some(&format!("IBL Params Buffer Env {}", env_map.id)),
            contents: bytemuck::cast_slice(&[env_uniform]),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });

        // Create bind group for fragment shader sampling
        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some(&format!("IBL Bind Group Env {}", env_map.id)),
            layout: &self.bind_group_layout,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::TextureView(&irradiance.view),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Sampler(&irradiance.sampler),
                },
                wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::TextureView(&prefiltered.view),
                },
                wgpu::BindGroupEntry {
                    binding: 3,
                    resource: wgpu::BindingResource::Sampler(&prefiltered.sampler),
                },
                wgpu::BindGroupEntry {
                    binding: 4,
                    resource: wgpu::BindingResource::TextureView(&self.brdf_lut.view),
                },
                wgpu::BindGroupEntry {
                    binding: 5,
                    resource: wgpu::BindingResource::Sampler(&self.brdf_lut.sampler),
                },
                wgpu::BindGroupEntry {
                    binding: 6,
                    resource: params_buffer.as_entire_binding(),
                },
            ],
        });

        // Store processed environment
        self.processed_environments.insert(
            env_map.id,
            (
                ProcessedEnvironment {
                    params_buffer,
                    bind_group,
                },
                env_map.generation(),
            ),
        );
    }

    /// Update the environment params uniform buffer (intensity) without reprocessing textures.
    fn update_env_params(&self, queue: &wgpu::Queue, env_map: &EnvironmentMap) {
        if let Some((processed, _)) = self.processed_environments.get(&env_map.id) {
            let env_uniform = EnvironmentUniform {
                intensity: env_map.intensity(),
                _padding: [0; 3],
            };
            queue.write_buffer(
                &processed.params_buffer,
                0,
                bytemuck::cast_slice(&[env_uniform]),
            );
        }
    }

    /// Get the processed environment for an ID, if available.
    pub fn get_processed(&self, id: EnvironmentMapId) -> Option<&ProcessedEnvironment> {
        self.processed_environments.get(&id).map(|(env, _)| env)
    }

    /// Remove a processed environment.
    pub fn _remove_processed(&mut self, id: EnvironmentMapId) {
        self.processed_environments.remove(&id);
    }

    /// Preprocess an environment map into CPU-side IBL data via GPU compute shaders.
    ///
    /// Runs the full IBL pipeline (equirect→cubemap→irradiance+prefiltered) and
    /// reads the results back from the GPU. The returned [`PreprocessedIbl`] can be
    /// attached to an [`EnvironmentMap`] and serialized into a scene file.
    ///
    /// Requires compute shaders to be available (`has_compute == true`).
    pub fn preprocess_ibl(
        &self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        env_map: &EnvironmentMap,
    ) -> anyhow::Result<PreprocessedIbl> {
        anyhow::ensure!(
            self.has_compute,
            "Cannot preprocess IBL without compute shader support"
        );

        let hdr_image = match env_map.source() {
            EnvironmentSource::EquirectangularPath(path) => load_hdr_from_path(path)?,
            EnvironmentSource::EquirectangularHdr(bytes) => load_hdr_from_bytes(bytes)?,
            EnvironmentSource::Preprocessed => {
                anyhow::bail!("Environment map already has only preprocessed data (no HDR source)");
            }
        };

        let equirect = self.equirect_pipeline.as_ref().unwrap();
        let irradiance_pipeline = self.irradiance_pipeline.as_ref().unwrap();
        let prefilter_pipeline = self.prefilter_pipeline.as_ref().unwrap();

        let environment = equirect.convert(device, queue, &hdr_image);
        let irradiance = irradiance_pipeline.generate(device, queue, &environment);
        let prefiltered = prefilter_pipeline.generate(device, queue, &environment);

        let bytes_per_pixel = 8; // Rgba16Float

        let irradiance_data = irradiance.readback(
            device,
            queue,
            IRRADIANCE_CUBEMAP_SIZE,
            1,
            bytes_per_pixel,
        );
        let prefiltered_data = prefiltered.readback(
            device,
            queue,
            PREFILTERED_CUBEMAP_SIZE,
            PREFILTERED_MIP_LEVELS,
            bytes_per_pixel,
        );

        Ok(PreprocessedIbl {
            irradiance: irradiance_data,
            prefiltered: prefiltered_data,
            brdf_lut: None,
        })
    }
}

/// Upload a [`PreprocessedCubemap`] to a [`GpuCubemap`] via `queue.write_texture()`.
///
/// The preprocessed data is in Rgba16Float format (8 bytes per pixel), matching the
/// GPU texture format directly.
fn upload_preprocessed_cubemap(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    data: &PreprocessedCubemap,
    label: &str,
) -> GpuCubemap {
    let cubemap = GpuCubemap::new(
        device,
        data.face_size,
        wgpu::TextureFormat::Rgba16Float,
        data.mip_levels,
        wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        label,
    );

    let bytes_per_pixel: u32 = 8; // Rgba16Float

    for (mip, mip_faces) in data.mip_data.iter().enumerate() {
        let mip_size = data.face_size >> mip as u32;
        let bytes_per_row = mip_size * bytes_per_pixel;

        for (face, face_data) in mip_faces.iter().enumerate() {
            queue.write_texture(
                wgpu::TexelCopyTextureInfo {
                    texture: &cubemap.texture,
                    mip_level: mip as u32,
                    origin: wgpu::Origin3d {
                        x: 0,
                        y: 0,
                        z: face as u32,
                    },
                    aspect: wgpu::TextureAspect::All,
                },
                face_data,
                wgpu::TexelCopyBufferLayout {
                    offset: 0,
                    bytes_per_row: Some(bytes_per_row),
                    rows_per_image: Some(mip_size),
                },
                wgpu::Extent3d {
                    width: mip_size,
                    height: mip_size,
                    depth_or_array_layers: 1,
                },
            );
        }
    }

    cubemap
}
