//! BRDF integration lookup table generation.
//!
//! Generates a 2D LUT used in the split-sum approximation for specular IBL.
//! The LUT stores pre-integrated BRDF terms that can be looked up at runtime
//! using N·V and roughness as coordinates.
//!
//! The LUT can be created in two ways:
//! - **Baked (from_baked)**: Loaded from a pre-computed binary generated by `build.rs`.
//!   Always available, no compute shaders needed.
//! - **Computed (BrdfLutPipeline)**: Generated at runtime via GPU compute shader.
//!   Used when compute shaders are available and provides identical results.

use crate::ibl::BRDF_LUT_SIZE;

/// Baked BRDF LUT data generated by build.rs.
/// Format: 512x512 pixels, 4 channels (RGBA), f32 per channel, little-endian.
const BAKED_BRDF_LUT: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/brdf_lut.bin"));

/// Shader source for BRDF LUT generation.
const BRDF_LUT_SHADER: &str = include_str!("../shaders/ibl/brdf_lut.wgsl");

/// GPU resources for the BRDF lookup table.
#[derive(Debug)]
pub struct BrdfLut {
    pub _texture: wgpu::Texture,
    pub view: wgpu::TextureView,
    pub sampler: wgpu::Sampler,
}

impl BrdfLut {
    /// Create a BRDF LUT from the baked data generated by build.rs.
    ///
    /// This converts f32 data to Rgba16Float and uploads it via `queue.write_texture()`.
    /// No compute shaders needed — works on all platforms including WebGL.
    pub fn from_baked(device: &wgpu::Device, queue: &wgpu::Queue) -> Self {
        let texture = device.create_texture(&wgpu::TextureDescriptor {
            label: Some("BRDF LUT Texture (Baked)"),
            size: wgpu::Extent3d {
                width: BRDF_LUT_SIZE,
                height: BRDF_LUT_SIZE,
                depth_or_array_layers: 1,
            },
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Rgba16Float,
            usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
            view_formats: &[],
        });

        // Convert f32 RGBA to f16 RGBA
        let pixel_count = (BRDF_LUT_SIZE * BRDF_LUT_SIZE) as usize;
        let f32_data: &[f32] = bytemuck::cast_slice(BAKED_BRDF_LUT);
        let mut f16_data = vec![0u16; pixel_count * 4];
        for i in 0..f32_data.len() {
            f16_data[i] = half::f16::from_f32(f32_data[i]).to_bits();
        }

        let bytes_per_pixel = 8; // Rgba16Float = 4 * 2 bytes
        queue.write_texture(
            wgpu::TexelCopyTextureInfo {
                texture: &texture,
                mip_level: 0,
                origin: wgpu::Origin3d::ZERO,
                aspect: wgpu::TextureAspect::All,
            },
            bytemuck::cast_slice(&f16_data),
            wgpu::TexelCopyBufferLayout {
                offset: 0,
                bytes_per_row: Some(BRDF_LUT_SIZE * bytes_per_pixel),
                rows_per_image: Some(BRDF_LUT_SIZE),
            },
            wgpu::Extent3d {
                width: BRDF_LUT_SIZE,
                height: BRDF_LUT_SIZE,
                depth_or_array_layers: 1,
            },
        );

        let view = texture.create_view(&wgpu::TextureViewDescriptor::default());

        let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("BRDF LUT Sampler"),
            address_mode_u: wgpu::AddressMode::ClampToEdge,
            address_mode_v: wgpu::AddressMode::ClampToEdge,
            address_mode_w: wgpu::AddressMode::ClampToEdge,
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::FilterMode::Nearest,
            ..Default::default()
        });

        Self {
            _texture: texture,
            view,
            sampler,
        }
    }
}

/// Pipeline for generating the BRDF lookup table.
pub struct BrdfLutPipeline {
    pipeline: wgpu::ComputePipeline,
    bind_group_layout: wgpu::BindGroupLayout,
}

impl BrdfLutPipeline {
    /// Create a new BRDF LUT generation pipeline.
    pub fn new(device: &wgpu::Device) -> Self {
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("BRDF LUT Shader"),
            source: wgpu::ShaderSource::Wgsl(BRDF_LUT_SHADER.into()),
        });

        let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("BRDF LUT Bind Group Layout"),
            entries: &[
                // Output LUT storage texture
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::StorageTexture {
                        access: wgpu::StorageTextureAccess::WriteOnly,
                        // Rg16Float doesn't support STORAGE_BINDING, use Rgba16Float instead
                        format: wgpu::TextureFormat::Rgba16Float,
                        view_dimension: wgpu::TextureViewDimension::D2,
                    },
                    count: None,
                },
            ],
        });

        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("BRDF LUT Pipeline Layout"),
            bind_group_layouts: &[&bind_group_layout],
            push_constant_ranges: &[],
        });

        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("BRDF LUT Pipeline"),
            layout: Some(&pipeline_layout),
            module: &shader,
            entry_point: Some("main"),
            compilation_options: Default::default(),
            cache: None,
        });

        Self {
            pipeline,
            bind_group_layout,
        }
    }

    /// Generate the BRDF lookup table.
    ///
    /// This only needs to be done once - the LUT is independent of the environment map.
    pub fn generate(&self, device: &wgpu::Device, queue: &wgpu::Queue) -> BrdfLut {
        // Create output texture
        let texture = device.create_texture(&wgpu::TextureDescriptor {
            label: Some("BRDF LUT Texture"),
            size: wgpu::Extent3d {
                width: BRDF_LUT_SIZE,
                height: BRDF_LUT_SIZE,
                depth_or_array_layers: 1,
            },
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            // Rg16Float doesn't support STORAGE_BINDING, use Rgba16Float instead
            format: wgpu::TextureFormat::Rgba16Float,
            usage: wgpu::TextureUsages::STORAGE_BINDING | wgpu::TextureUsages::TEXTURE_BINDING,
            view_formats: &[],
        });

        let view = texture.create_view(&wgpu::TextureViewDescriptor::default());

        let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("BRDF LUT Sampler"),
            address_mode_u: wgpu::AddressMode::ClampToEdge,
            address_mode_v: wgpu::AddressMode::ClampToEdge,
            address_mode_w: wgpu::AddressMode::ClampToEdge,
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::FilterMode::Nearest,
            ..Default::default()
        });

        // Create bind group
        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("BRDF LUT Bind Group"),
            layout: &self.bind_group_layout,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::TextureView(&view),
            }],
        });

        // Dispatch compute shader
        let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
            label: Some("BRDF LUT Encoder"),
        });

        {
            let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                label: Some("BRDF LUT Pass"),
                timestamp_writes: None,
            });
            pass.set_pipeline(&self.pipeline);
            pass.set_bind_group(0, &bind_group, &[]);

            let workgroups_x = (BRDF_LUT_SIZE + 15) / 16;
            let workgroups_y = (BRDF_LUT_SIZE + 15) / 16;
            pass.dispatch_workgroups(workgroups_x, workgroups_y, 1);
        }

        queue.submit(std::iter::once(encoder.finish()));

        BrdfLut {
            _texture: texture,
            view,
            sampler,
        }
    }
}
